/// <reference types="node" />

/**
 * Cleanup script — removes all generated artifacts before a fresh orchestration run.
 *
 * Removes:
 *   - Every plan .md file listed under planFiles / planFile in orchestrator.config.json
 *   - The generatedTestsFolder (tests/generated by default)
 *   - The reportsFolder (reports by default)
 *   - test-results/   (Playwright failure artefacts)
 *   - playwright-report/  (Playwright HTML report)
 *
 * Files NOT touched:
 *   - specs/README.md (and any .md not referenced by config)
 *   - tests/ source files (auth.setup.ts, fixtures.ts, seed.spec.ts, helpers/, …)
 *   - .env, package.json, tsconfig.json, orchestrator.config.json, etc.
 *
 * Usage:
 *   npm run cleanup
 */

import fs = require("node:fs/promises");
import path = require("node:path");
import process = require("node:process");
import "dotenv/config";

interface PlanTarget { file: string; scope: string; }
interface OrchestratorConfig {
  planFile?: string;
  planFiles?: PlanTarget[];
  generatedTestsFolder: string;
  reportsFolder: string;
}

async function remove(target: string, label: string): Promise<void> {
  const stat = await fs.stat(target).catch(() => undefined);
  if (!stat) {
    console.log(`  skip  ${label} (not found)`);
    return;
  }
  await fs.rm(target, { recursive: true, force: true });
  console.log(`  removed  ${label}`);
}

async function main(): Promise<void> {
  const root = process.cwd();
  const configPath = path.join(root, "orchestrator.config.json");

  let config: OrchestratorConfig;
  try {
    config = JSON.parse(await fs.readFile(configPath, "utf8")) as OrchestratorConfig;
  } catch {
    console.error(`Cannot read orchestrator.config.json at ${configPath}`);
    process.exitCode = 1;
    return;
  }

  console.log("\nCleaning up generated artifacts...\n");

  // ── Plan files ────────────────────────────────────────────────────────────
  const planFiles: string[] = [
    ...(config.planFiles?.map((p) => p.file) ?? []),
    ...(config.planFile ? [config.planFile] : []),
  ];

  for (const rel of planFiles) {
    await remove(path.resolve(root, rel), `plan  ${rel}`);
  }

  // ── Generated tests ───────────────────────────────────────────────────────
  await remove(
    path.resolve(root, config.generatedTestsFolder),
    `generated tests  ${config.generatedTestsFolder}/`,
  );

  // ── Reports ───────────────────────────────────────────────────────────────
  await remove(
    path.resolve(root, config.reportsFolder),
    `reports  ${config.reportsFolder}/`,
  );

  // ── Playwright artefacts ──────────────────────────────────────────────────
  await remove(path.join(root, "test-results"),     "test-results/");
  await remove(path.join(root, "playwright-report"), "playwright-report/");

  console.log("\nDone. Ready for a fresh run: npm run generate\n");
}

void main().catch((err: unknown) => {
  console.error("Cleanup error:", err instanceof Error ? err.message : String(err));
  process.exitCode = 1;
});
